apiVersion: operators.coreos.com/v1alpha1
kind: ClusterServiceVersion
metadata:
  annotations:
    alm-examples: |-
      [
        {
          "apiVersion": "operator.openshift.io/v1",
          "kind": "CliManager",
          "metadata": {
            "name": "cluster",
            "namespace": "openshift-cli-manager-operator"
          },
          "spec": {
            "logLevel": "Normal",
            "managementState": "Managed",
            "operatorLogLevel": "Normal"
          }
        }
      ]
    capabilities: Basic Install
    createdAt: "2024-06-04T11:01:49Z"
    operators.operatorframework.io/builder: operator-sdk-v1.34.2
  name: cli-manager-operator.v0.1
  namespace: openshift-cli-manager-operator
spec:
  customresourcedefinitions:
    owned:
    - kind: CliManager
      name: climanagers.operator.openshift.io
      version: v1
    - kind: Plugin
      name: plugins.config.openshift.io
      version: v1alpha1
  description: An operator to manage CLI Manager
  displayName: Cli Manager Operator
  install:
    spec:
      clusterPermissions:
      - rules:
        - apiGroups:
          - operator.openshift.io
          resources:
          - climanagers
          - climanagers/status
          verbs:
          - '*'
        - apiGroups:
          - config.openshift.io
          resources:
          - plugins
          verbs:
          - '*'
        - apiGroups:
          - coordination.k8s.io
          resources:
          - leases
          verbs:
          - get
          - watch
          - list
          - create
          - update
        - apiGroups:
          - rbac.authorization.k8s.io
          resources:
          - clusterroles
          - clusterrolebindings
          verbs:
          - '*'
        - apiGroups:
          - apps
          resources:
          - deployments
          verbs:
          - '*'
        - apiGroups:
          - ""
          resources:
          - services
          - serviceaccounts
          - events
          - pods
          verbs:
          - '*'
        - apiGroups:
          - route.openshift.io
          resources:
          - routes
          verbs:
          - '*'
        - apiGroups:
          - config.openshift.io
          resources:
          - infrastructures
          - apiservers
          verbs:
          - get
          - watch
          - list
        serviceAccountName: openshift-cli-manager-operator
      deployments:
      - name: openshift-cli-manager-operator
        spec:
          replicas: 1
          selector:
            matchLabels:
              name: openshift-cli-manager-operator
          strategy: {}
          template:
            metadata:
              labels:
                name: openshift-cli-manager-operator
            spec:
              containers:
              - args:
                - operator
                command:
                - cli-manager-operator
                env:
                - name: WATCH_NAMESPACE
                  valueFrom:
                    fieldRef:
                      fieldPath: metadata.annotations['olm.targetNamespaces']
                - name: OPERATOR_NAME
                  value: openshift-cli-manager-operator
                - name: RELATED_IMAGE_OPERAND_IMAGE
                  value: quay.io/openshift/origin-cli-manager:latest
                image: quay.io/openshift/origin-cli-manager-operator:latest
                imagePullPolicy: Always
                name: openshift-cli-manager-operator
                ports:
                - containerPort: 60000
                  name: metrics
                resources: {}
              serviceAccountName: openshift-cli-manager-operator
    strategy: deployment
  installModes:
  - supported: true
    type: OwnNamespace
  - supported: true
    type: SingleNamespace
  - supported: false
    type: MultiNamespace
  - supported: false
    type: AllNamespaces
  keywords:
  - cli-manager-operator
  links:
    - name: Source Code
      url: https://github.com/openshift/cli-manager
    - name: Source Code
      url: https://github.com/openshift/cli-manager-operator
  maintainers:
  - email: support@redhat.com
    name: Red Hat
  maturity: alpha
  provider:
    name: Red Hat, Inc.
  version: 0.1
