apiVersion: operator.openshift.io/v1
kind: CliManager
metadata:
  name: cluster
  namespace: openshift-cli-manager-operator
spec:
  managementState: Managed
  logLevel: Normal
  operatorLogLevel: Normal