apiVersion: apps/v1
kind: Deployment
metadata:
  name: openshift-cli-manager-operator
  namespace: openshift-cli-manager-operator
spec:
  replicas: 1
  selector:
    matchLabels:
      name: openshift-cli-manager-operator
  template:
    metadata:
      labels:
        name: openshift-cli-manager-operator
    spec:
      containers:
        - name: openshift-cli-manager-operator
          image: quay.io/openshift/origin-cli-manager-operator:latest
          ports:
            - containerPort: 60000
              name: metrics
          command:
            - openshift-cli-manager-operator
          args:
            - "operator"
          imagePullPolicy: Always
          env:
            - name: WATCH_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: OPERATOR_NAME
              value: "openshift-cli-manager-operator"
            - name: IMAGE
              value: quay.io/openshift/origin-cli-manager:4.16
      serviceAccountName: openshift-cli-manager-operator